web:
  build: .
  dockerfile: nginxDockerfile

  volumes:
    - ./public/:/app/
  ports:
    - "80:80"

  links:
    - server

  mem_limit: 8m

server:
  build: .
  dockerfile: pythonDockerfile

  volumes:
    - ./server:/back

  working_dir: /back

  ports:
    - "8765:8765"

  mem_limit: 16m
